server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: keycloak-demo
  auth-server-url: http://localhost:8080
  resource: springboot-keycloak
  public-client: true
  bearer-only: true